/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import ConnectionDB.ConnectDB;
import static IHM.confiramation.RET_OK;
import Model.AchatM;
import Model.Facture;
import Model.VenteM;
import Model.bonrecu;
import Model.detailsAchat;
import Model.detailsFcture;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Abderrazak
 */
public class Achat extends javax.swing.JFrame {

    /**
     * Creates new form Achat
     */
    public Achat() {
     
          initComponents();
          
//          AutoCompleteDecorator.decorate(NMF);
//           AutoCompleteDecorator.decorate(NMP);
showDate();
       showTime();
       icon();
    }ConnectDB db ; 
      void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("iconapp.png")));
    }
  void showDate(){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("E dd-MM-YYYY");
    jLabel16.setText(sdf.format(d));
            
}
void showTime(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date d=new Date();
             SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
   jLabel13.setText(sdf.format(d));
        }
    }).start();
}
 public void getSum()
    {
        int sum = 0;
        for(int i = 0; i < TBV.getRowCount(); i++)
        {
                sum = sum+Integer.parseInt(TBV.getValueAt(i,8).toString());
               
        }
        
       total.setText(Integer.toString(sum));
  
    }
 public void getMontant_HT()
    {
        int sum = 0;
        for(int i = 0; i < TBV.getRowCount(); i++)
        {
                sum = sum+Integer.parseInt(TBV.getValueAt(i,8).toString());
               
        }
        
       total.setText(Integer.toString(sum));
  
    }
public int checkJTable(JTable TBV, String element) {
    boolean found = false;
    for (int i = 0; i < TBV.getRowCount(); i++) {
        for (int j = 0; j < TBV.getColumnCount(); j++) {
            if (TBV.getValueAt(i, j).equals(element)) {
                found = true;
                break;
            }
        }
        if (found) {
            break;
        }
    }
    if (found) {
      return 1;
    } else {
       return 0;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cmdClose4 = new com.raven.swing.win_button.Button();
        cmdMi4 = new com.raven.swing.win_button.Button();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        prixuntaire = new textfield.TextField();
        qnt = new textfield.TextField();
        total = new button.Button();
        nf1 = new button.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBV = new tabledark.TableDark();
        nomfournisseur = new combobox.Combobox();
        Matier = new combobox.Combobox();
        prixvente = new textfield.TextField();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1610, 963));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1901, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 114, 169));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/achats .png"))); // NOI18N
        jLabel1.setText("Achats");

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("date");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/date.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("time");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock (1).png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(17, 114, 169));

        cmdClose4.setBackground(new java.awt.Color(240, 61, 61));
        cmdClose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClose4ActionPerformed(evt);
            }
        });

        cmdMi4.setBackground(new java.awt.Color(227, 226, 68));
        cmdMi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMi4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(cmdClose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdMi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdClose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMi4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(432, 432, 432)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1630, 60));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel4.setText("Designation :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel5.setText("Prix Untaire :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText("Nom de Fournisseur :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel6.setText("Métrage :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        jButton1.setText("Imprimer ");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDefaultCapable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 640, -1, -1));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnew.png"))); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDefaultCapable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, -1, -1));

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash_1.png"))); // NOI18N
        jButton4.setText("supprimer ");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDefaultCapable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 100, -1, -1));

        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refrach.png"))); // NOI18N
        jButton5.setText("actualise");
        jButton5.setActionCommand("Actuliser");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setDefaultCapable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 510, -1, -1));

        prixuntaire.setForeground(new java.awt.Color(0, 0, 0));
        prixuntaire.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        prixuntaire.setSelectionColor(new java.awt.Color(0, 0, 0));
        prixuntaire.setShadowColor(new java.awt.Color(0, 0, 0));
        prixuntaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixuntaireActionPerformed(evt);
            }
        });
        jPanel1.add(prixuntaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 212, -1));

        qnt.setForeground(new java.awt.Color(0, 0, 0));
        qnt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        qnt.setSelectionColor(new java.awt.Color(0, 0, 0));
        qnt.setShadowColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(qnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 212, -1));

        total.setBackground(new java.awt.Color(0, 0, 0));
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("Totale :");
        total.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 850, 180, 72));

        nf1.setBackground(new java.awt.Color(0, 0, 0));
        nf1.setForeground(new java.awt.Color(255, 255, 255));
        nf1.setText("N°Achat");
        nf1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        nf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nf1ActionPerformed(evt);
            }
        });
        jPanel1.add(nf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        TBV.setAutoCreateRowSorter(true);
        TBV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°produit", "Designation", "fournisseur", "Métrage", "PrixUntaire", "PrixVente", "Montant_HT", "Montant_TVA", "Montant_TTC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBV.setDropMode(javax.swing.DropMode.ON);
        TBV.setFillsViewportHeight(true);
        TBV.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        TBV.getTableHeader().setReorderingAllowed(false);
        TBV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBV);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 1370, 402));

        nomfournisseur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        nomfournisseur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAISISSEZ VOTRE CHOIIX" }));
        nomfournisseur.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nomfournisseur.setLabeText("");
        nomfournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomfournisseurActionPerformed(evt);
            }
        });
        jPanel1.add(nomfournisseur, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 260, -1));

        Matier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        Matier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAISISSEZ VOTRE CHOIIX" }));
        Matier.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Matier.setLabeText("");
        Matier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatierActionPerformed(evt);
            }
        });
        jPanel1.add(Matier, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 204, 260, -1));

        prixvente.setForeground(new java.awt.Color(0, 0, 0));
        prixvente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        prixvente.setSelectionColor(new java.awt.Color(0, 0, 0));
        prixvente.setShadowColor(new java.awt.Color(0, 0, 0));
        prixvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixventeActionPerformed(evt);
            }
        });
        jPanel1.add(prixvente, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 212, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel7.setText("Prix Vente :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clipboard.png"))); // NOI18N
        jButton6.setText("Liste Achat");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 100, -1, 90));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/AAch.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addplus.png"))); // NOI18N
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

MessageFormat header = new MessageFormat("FACTURE : \n");
MessageFormat footer = new MessageFormat("Page {0,number,integer}");
try {
    // Créez une instance de JTable.PrintMode pour spécifier le mode d'impression
    JTable.PrintMode mode = JTable.PrintMode.FIT_WIDTH;

    // Créez un objet PrinterJob pour gérer l'impression
    PrinterJob printerJob = PrinterJob.getPrinterJob();

    // Obtenez la JTable que vous souhaitez imprimer (remplacez TBS par votre propre JTable)
    JTable table = TBV;

    // Créez un objet Printable à partir de la JTable
    Printable printable = table.getPrintable(mode, header, footer);

    // Définissez le document à imprimer sur l'objet Printable
    printerJob.setPrintable(printable);

    // Affichez la boîte de dialogue de paramètres d'impression (optionnel)
    if (printerJob.printDialog()) {
        // Lancez l'impression
        printerJob.print();
    }
} catch (PrinterException e) {
    System.err.println("Erreur d'impression : " + e.getMessage());
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        int quntite; String MatierM =  (String)Matier.getSelectedItem();
         int i;

       
            i= TBV.getSelectedRow();
          
           quntite= (int) TBV.getValueAt(i, 3);
           int IDProduit =db.FindIDProduit((String) Matier.getSelectedItem());
        suprime dialog = new suprime(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
        if(dialog.getReturnStatus()==suprime.RET_OK){
            int qnt=   db.Findqntiteproduit(MatierM)-quntite;
 db.changeQnt(IDProduit, qnt);
            
            
        int valeur = (int) TBV.getValueAt(TBV.getSelectedRow(),8);
    int  montant = Integer.parseInt(total.getText());
int sum;
sum = montant-valeur;

total.setText(Integer.toString(sum));
        DefaultTableModel model = (DefaultTableModel) TBV.getModel();
 
       try{
       int SelectedRowIndex = TBV.getSelectedRow();
       model.removeRow(SelectedRowIndex);
       }catch(Exception ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }
        ;
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
  
          db =new ConnectDB();
       db.ConnexionIntoDataBase();
        db.FindNomMatier(Matier);
        db.FindNomFournisseur(nomfournisseur);
try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\achat.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(1500);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        }     
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
String ncbPatternString = "^[0-9]+$";
String aifPatternString = "^[0-9]+$";
String nisPatternString = "^[0-9]+$";

Pattern ncbPattern = Pattern.compile(ncbPatternString);
Pattern aifPattern = Pattern.compile(aifPatternString);
Pattern nisPattern = Pattern.compile(nisPatternString);

Matcher ncbMatcher = ncbPattern.matcher(prixuntaire.getText());
Matcher aifMatcher = aifPattern.matcher(qnt.getText());
Matcher nisMatcher = nisPattern.matcher(prixvente.getText());   
if ( !ncbMatcher.matches() || !aifMatcher.matches() || !nisMatcher.matches()  ) {
    // L'adresse e-mail ou le numéro de téléphone n'est pas au bon format, affichez un message d'erreur ou une notification appropriée
//    JOptionPane.showMessageDialog(null, "prix vent eou prix untaire ou qantite ", "Erreur", JOptionPane.ERROR_MESSAGE);
ERREUR dialog = new ERREUR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
}else{
        int qnte=  db.Findqntiteproduit((String) Matier.getSelectedItem()); 
  int quntite = Integer.parseInt(qnt.getText()); 

  if(quntite == 0  || quntite<0 ){System.out.println("IHM.Vent.jButton1ActionPerformed()");
            QANTITE dialog = new QANTITE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
   qnt.setText("");
                  qnt.requestFocus();} 
  else{
      
      System.out.println("IHM.khya nermal.jButton1ActionPerformed()");
        int valeur= checkJTable(TBV,(String)Matier.getSelectedItem());
        
        if(valeur==0){
            String matier=(String) Matier.getSelectedItem();
        int IDProduit =db.FindIDProduit((String) Matier.getSelectedItem());
           String MatierM =  (String)Matier.getSelectedItem();
       int prixunitare =  Integer.parseInt(prixuntaire.getText()); 

    
//     int quntite = Integer.parseInt(qnt.getText()); 
            ArrayList<AchatM> list = new ArrayList<AchatM>();
         int PV=Integer.parseInt(prixvente.getText());
         int Montant_HT=(prixunitare*quntite);
int Montant_TVA=(int) (Montant_HT*0.19);
int Montant_TTC=Montant_TVA+Montant_HT;
        AchatM V = new AchatM(IDProduit,MatierM, (String) nomfournisseur.getSelectedItem(),quntite,prixunitare,PV,Montant_HT,Montant_TVA, Montant_TTC);
              db.SPRIX(V,MatierM);
              list.add(V);
            

            DefaultTableModel mo = (DefaultTableModel) TBV.getModel();
       
         
            Object  row[] = new Object[9];
            int i=0;
//            mo.setRowCount(ABORT);
            for (int k = 0; k < list.size(); k++) {
               
                row[0] = list.get(k).getId_produit();
                row[1] = list.get(k).getDesignation();
               
                row[2] = list.get(k).getNomfournisseur();
                row[3] = list.get(k).getQuantité();
             
                row[4] = list.get(k).getPrix_unitaire();
                row[5] = list.get(k).getPV();
                  row[6] = list.get(k).getMontant_HT();
             
                row[7] = list.get(k).getMontant_TVA();
                row[8] = list.get(k).getMontant_TTC();
                
  
               mo.addRow(row);
                prixuntaire.setText("");
                  prixvente.setText("");
                  qnt.setText("");
                  prixuntaire.requestFocus();
 }
            getMontant_HT();
//        System.out.println("IHM.Vent.ValidActionPerformed()"+ db.Findqntiteproduit(MatierM));    
 int qnt=   db.Findqntiteproduit(MatierM)+quntite;
 db.changeQnt(IDProduit, qnt);
            System.err.println("facture");
            int id_Fournisseur=db.FindIDFornis((String) nomfournisseur.getSelectedItem());
   bonrecu f= new bonrecu(id_Fournisseur,db.showDate(),db.showDateTime(),Montant_TTC); 
   
      System.err.println("insert to facture ");
   db.inserttoAchat(f);  String user =db.GETUSER();
   
 detailsAchat df=new detailsAchat( db.FindidAchat(id_Fournisseur),IDProduit, prixunitare, quntite,Montant_TTC ,PV, user, MatierM, (String) nomfournisseur.getSelectedItem());
   db.inserttoDtailsAchat(df);
            
       } else {
        
        
        ErreurVent dialog = new ErreurVent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
        
        
        if(dialog.getReturnStatus()==ErreurVent.RET_CANCEL){
      
       Matier.requestFocus();
        }
        }     
        }  
       } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void nf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nf1ActionPerformed

    private void TBVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBVMouseClicked
        int i;

//        try{
////            i= TBV.getSelectedRow();
////            np.setText( TBV.getValueAt(i, 0)+"");
////
////        }catch(Exception e){
//
//        }

    }//GEN-LAST:event_TBVMouseClicked

    private void nomfournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomfournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomfournisseurActionPerformed

    private void MatierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MatierActionPerformed

    private void prixuntaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixuntaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixuntaireActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   Home c=new Home();
        c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//      Achat c=new Achat();
//        c.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void prixventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixventeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixventeActionPerformed

    private void cmdClose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClose4ActionPerformed
try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\bay.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdClose4ActionPerformed

    private void cmdMi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMi4ActionPerformed
try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\quitte achat.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
        this.setState(JFrame.ICONIFIED);    
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_cmdMi4ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DetailsAchat d=new DetailsAchat();
        d.setVisible(true);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Fournniseur p = new Fournniseur();
p.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Produit p = new Produit();
p.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Achat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Achat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Achat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Achat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Achat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combobox.Combobox Matier;
    private tabledark.TableDark TBV;
    private com.raven.swing.win_button.Button cmdClose4;
    private com.raven.swing.win_button.Button cmdMi4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private button.Button nf1;
    private combobox.Combobox nomfournisseur;
    private textfield.TextField prixuntaire;
    private textfield.TextField prixvente;
    private textfield.TextField qnt;
    private button.Button total;
    // End of variables declaration//GEN-END:variables
}
