/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import ConnectionDB.ConnectDB;
import Model.ClientM;
import Model.FournisseurM;
import static IHM.confiramation.RET_OK;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.*;
/**
 *
 * @author Abderrazak
 */
public class Fournniseur extends javax.swing.JFrame {

   
    public Fournniseur() {
        
        initComponents();
        icon();
       showDate();
       showTime();
    } ConnectDB db;
  void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("iconapp.png")));
    }
     void showDate(){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("E dd-MM-YYYY");
    jLabel16.setText(sdf.format(d));
            
}
void showTime(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date d=new Date();
             SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
   jLabel13.setText(sdf.format(d));
        }
    }).start();
}
 public int checkJTable(JTable TBV, String element) {
    boolean found = false;
    for (int i = 0; i < TBV.getRowCount(); i++) {
        for (int j = 0; j < TBV.getColumnCount(); j++) {
            if (TBV.getValueAt(i, j).equals(element)) {
                found = true;
                break;
            }
        }
        if (found) {
            break;
        }
    }
    if (found) {
      return 1;
    } else {
       return 0;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cmdClose = new com.raven.swing.win_button.Button();
        cmdMi = new com.raven.swing.win_button.Button();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBF = new tabledark.TableDark();
        nf = new button.Button();
        nom = new textfield.TextField();
        mobile = new textfield.TextField();
        email = new textfield.TextField();
        adrasse = new textfield.TextField();
        nrc = new textfield.TextField();
        ai = new textfield.TextField();
        aif = new textfield.TextField();
        nis = new textfield.TextField();
        tin = new textfield.TextField();
        jLabel12 = new javax.swing.JLabel();
        srch = new textfield.TextField();

        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1610, 963));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 114, 169));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Documents\\man_with_beard_in_suit_50px.png")); // NOI18N
        jLabel1.setText("Fournisseur");

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("date");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/date.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("time");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock (1).png"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(17, 114, 169));

        cmdClose.setBackground(new java.awt.Color(240, 61, 61));
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        cmdMi.setBackground(new java.awt.Color(227, 226, 68));
        cmdMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 433, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(411, 411, 411)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 60));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText("Adrasse :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel4.setText("Mobile :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel7.setText("TIN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel8.setText("NIS:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel9.setText("AIF:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel10.setText("NCB :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editnew.png"))); // NOI18N
        jButton1.setText("Modifier");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 120, -1, -1));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/addnew.png"))); // NOI18N
        jButton3.setText("Ajouter");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 120, -1, -1));

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash_1.png"))); // NOI18N
        jButton4.setText("supprimer");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 120, -1, -1));

        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refrach.png"))); // NOI18N
        jButton5.setText("Actuliser");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 630, -1, -1));

        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        jButton6.setText("Imprime");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 760, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/charche.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel11.setText("N°RC :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        TBF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBF.setFillsViewportHeight(true);
        TBF.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        TBF.getTableHeader().setReorderingAllowed(false);
        TBF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBFMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 1370, 400));

        nf.setBackground(new java.awt.Color(0, 0, 0));
        nf.setForeground(new java.awt.Color(255, 255, 255));
        nf.setText("N°Fournisseur");
        nf.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        nf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nfActionPerformed(evt);
            }
        });
        jPanel1.add(nf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        nom.setForeground(new java.awt.Color(0, 0, 0));
        nom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nom.setSelectionColor(new java.awt.Color(0, 0, 0));
        nom.setShadowColor(new java.awt.Color(0, 0, 0));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomKeyReleased(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 212, -1));

        mobile.setForeground(new java.awt.Color(0, 0, 0));
        mobile.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        mobile.setSelectionColor(new java.awt.Color(0, 0, 0));
        mobile.setShadowColor(new java.awt.Color(0, 0, 0));
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        mobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobileKeyPressed(evt);
            }
        });
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 214, -1));

        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        email.setSelectionColor(new java.awt.Color(0, 0, 0));
        email.setShadowColor(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 214, -1));

        adrasse.setForeground(new java.awt.Color(0, 0, 0));
        adrasse.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        adrasse.setSelectionColor(new java.awt.Color(0, 0, 0));
        adrasse.setShadowColor(new java.awt.Color(0, 0, 0));
        adrasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrasseActionPerformed(evt);
            }
        });
        adrasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adrasseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adrasseKeyReleased(evt);
            }
        });
        jPanel1.add(adrasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 214, -1));

        nrc.setForeground(new java.awt.Color(0, 0, 0));
        nrc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nrc.setSelectionColor(new java.awt.Color(0, 0, 0));
        nrc.setShadowColor(new java.awt.Color(0, 0, 0));
        nrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrcActionPerformed(evt);
            }
        });
        nrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nrcKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nrcKeyReleased(evt);
            }
        });
        jPanel1.add(nrc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 214, -1));

        ai.setForeground(new java.awt.Color(0, 0, 0));
        ai.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ai.setSelectionColor(new java.awt.Color(0, 0, 0));
        ai.setShadowColor(new java.awt.Color(0, 0, 0));
        ai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aiKeyReleased(evt);
            }
        });
        jPanel1.add(ai, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 212, -1));

        aif.setForeground(new java.awt.Color(0, 0, 0));
        aif.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        aif.setSelectionColor(new java.awt.Color(0, 0, 0));
        aif.setShadowColor(new java.awt.Color(0, 0, 0));
        aif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aifActionPerformed(evt);
            }
        });
        aif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aifKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aifKeyReleased(evt);
            }
        });
        jPanel1.add(aif, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 214, -1));

        nis.setForeground(new java.awt.Color(0, 0, 0));
        nis.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nis.setSelectionColor(new java.awt.Color(0, 0, 0));
        nis.setShadowColor(new java.awt.Color(0, 0, 0));
        nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nisActionPerformed(evt);
            }
        });
        nis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nisKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nisKeyReleased(evt);
            }
        });
        jPanel1.add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 214, -1));

        tin.setForeground(new java.awt.Color(0, 0, 0));
        tin.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tin.setSelectionColor(new java.awt.Color(0, 0, 0));
        tin.setShadowColor(new java.awt.Color(0, 0, 0));
        tin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinActionPerformed(evt);
            }
        });
        tin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tinKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tinKeyReleased(evt);
            }
        });
        jPanel1.add(tin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 214, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel12.setText("Nom :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, -1, -1));

        srch.setForeground(new java.awt.Color(0, 0, 0));
        srch.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        srch.setSelectionColor(new java.awt.Color(0, 0, 0));
        srch.setShadowColor(new java.awt.Color(0, 0, 0));
        srch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchActionPerformed(evt);
            }
        });
        srch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srchKeyReleased(evt);
            }
        });
        jPanel1.add(srch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 214, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       db =new ConnectDB();
       db.ConnexionIntoDataBase();
       db.AllFOURNISEUR(TBF);
       try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\Fournniseur.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(1500);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        }     
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String nbr =mobile.getText();
            int code = Integer.parseInt(nbr);
      System.out.println("IHM.Fournniseur.jButton1ActionPerformed()"+Integer.parseInt(nf.getText()));
            FournisseurM cl=new FournisseurM(nom.getText(),code, email.getText(), adrasse.getText(),nrc.getText(), ai.getText(),aif.getText(),nis.getText(),tin.getText());
           
            db.UpdatFourniseur(Integer.parseInt(nf.getText()),cl);
           db.AllFOURNISEUR(TBF);

            

        }  catch(Exception e){
            JOptionPane.showMessageDialog(null, "ereur operation");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String emailPatternString = "^[A-Za-z0-9+.-]+@[A-Za-z0-9+.-]+\\.[A-Za-z0-9]+$";
String phonePatternString = "^[0-9]+$";
String ncbPatternString = "^[0-9]+$";
String aifPatternString = "^[0-9]+$";
String nisPatternString = "^[0-9]+$";
Pattern emailPattern = Pattern.compile(emailPatternString);
Pattern phonePattern = Pattern.compile(phonePatternString);
Pattern ncbPattern = Pattern.compile(ncbPatternString);
Pattern aifPattern = Pattern.compile(aifPatternString);
Pattern nisPattern = Pattern.compile(nisPatternString);
Matcher emailMatcher = emailPattern.matcher(email.getText());
Matcher phoneMatcher = phonePattern.matcher(mobile.getText());
Matcher ncbMatcher = ncbPattern.matcher(ai.getText());
Matcher aifMatcher = aifPattern.matcher(aif.getText());
Matcher nisMatcher = nisPattern.matcher(nis.getText());
 int valeur= checkJTable(TBF,(String)nom.getText());
        int valeur1= checkJTable(TBF,(String)mobile.getText());
if (!emailMatcher.matches() || !phoneMatcher.matches() || !ncbMatcher.matches() || !aifMatcher.matches() || !nisMatcher.matches()  ) {
    // L'adresse e-mail ou le numéro de téléphone n'est pas au bon format, affichez un message d'erreur ou une notification appropriée
     ERREUR dialog = new ERREUR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
}else if(valeur==0 && valeur1==0){
     confiramation dialog = new confiramation(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
 if(dialog.getReturnStatus()==confiramation.RET_OK){
        String nbr =mobile.getText();
        int code = Integer.parseInt(nbr);

     FournisseurM cl=new FournisseurM(nom.getText(),code, email.getText(), adrasse.getText(),nrc.getText(), ai.getText(),aif.getText(),nis.getText(), tin.getText());
        db.insertFornisseur(cl);
 }
 db.AllFOURNISEUR(TBF);
        mobile.setText("");
        nom.setText("");
        email.setText("");
        adrasse.setText("");
        tin.setText("");
        nrc.setText("");
        ai.setText("");
        aif.setText("");
        nis.setText("");
        nom.requestFocus();
}else{
       erourfourniseure dialog = new erourfourniseure(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        suprime dialog = new suprime(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
        if(dialog.getReturnStatus()==suprime.RET_OK){
            db.DeleteFourniseur(Integer.parseInt(nf.getText()));

        }else{
            System.err.println("ca s de erreur ");
        }
        db.AllFOURNISEUR(TBF);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        db.AllFOURNISEUR(TBF);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        MessageFormat header = new MessageFormat("Liste des FOURNISEUR : \n");
//        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
//
//        try {
//            TBF.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//        } catch (PrinterException ex) {
//            Logger.getLogger(Fournniseur.class.getName()).log(Level.SEVERE, null, ex);
//        }
MessageFormat header = new MessageFormat("Liste des FOURNISEURS : \n");
MessageFormat footer = new MessageFormat("Page {0,number,integer}");
try {
    // Créez une instance de JTable.PrintMode pour spécifier le mode d'impression
    JTable.PrintMode mode = JTable.PrintMode.FIT_WIDTH;

    // Créez un objet PrinterJob pour gérer l'impression
    PrinterJob printerJob = PrinterJob.getPrinterJob();

    // Obtenez la JTable que vous souhaitez imprimer (remplacez TBS par votre propre JTable)
    JTable table = TBF;

    // Créez un objet Printable à partir de la JTable
    Printable printable = table.getPrintable(mode, header, footer);

    // Définissez le document à imprimer sur l'objet Printable
    printerJob.setPrintable(printable);

    // Affichez la boîte de dialogue de paramètres d'impression (optionnel)
    if (printerJob.printDialog()) {
        // Lancez l'impression
        printerJob.print();
    }
} catch (PrinterException e) {
    System.err.println("Erreur d'impression : " + e.getMessage());
}

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.FindFourniseur(TBF, srch.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TBFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBFMouseClicked
        int i;

        try{
            i= TBF.getSelectedRow();
            nf.setText( TBF.getValueAt(i, 0)+"");
            nom.setText( TBF.getValueAt(i, 1)+"");
            mobile.setText( TBF.getValueAt(i, 2)+"");
            email.setText( TBF.getValueAt(i, 3)+"");
            adrasse.setText( TBF.getValueAt(i, 4)+"");
            nrc.setText( TBF.getValueAt(i, 5)+"");
            ai.setText( TBF.getValueAt(i, 6)+"");
            aif.setText( TBF.getValueAt(i, 7)+"");
            nis.setText( TBF.getValueAt(i, 8)+"");
            tin.setText( TBF.getValueAt(i, 9)+"");
          

        }catch(Exception e){

        }
    }//GEN-LAST:event_TBFMouseClicked

    private void nfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nfActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void adrasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adrasseActionPerformed

    private void nrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrcActionPerformed

    private void aifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aifActionPerformed

    private void nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nisActionPerformed

    private void tinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinActionPerformed

    private void srchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srchActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
  
    }//GEN-LAST:event_nomActionPerformed

    private void nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyPressed
      int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         mobile.requestFocus();
        }
    }//GEN-LAST:event_nomKeyPressed

    private void mobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileKeyPressed
       int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         email.requestFocus();
        }
    }//GEN-LAST:event_mobileKeyPressed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
     int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         adrasse.requestFocus();
        }
    }//GEN-LAST:event_emailKeyPressed

    private void adrasseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adrasseKeyPressed
      int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         nrc.requestFocus();
        }
    }//GEN-LAST:event_adrasseKeyPressed

    private void nrcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrcKeyPressed
     int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         ai.requestFocus();
        }
    }//GEN-LAST:event_nrcKeyPressed

    private void aiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aiKeyPressed
     int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         aif.requestFocus();
        }
    }//GEN-LAST:event_aiKeyPressed

    private void aifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aifKeyPressed
      int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         nis.requestFocus();
        }
    }//GEN-LAST:event_aifKeyPressed

    private void nisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisKeyPressed
       int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         tin.requestFocus();
        }
    }//GEN-LAST:event_nisKeyPressed

    private void tinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinKeyPressed
    int key=evt.getKeyCode();
     if((key!=10)){
     } else {
         jButton3.doClick();
        }
    }//GEN-LAST:event_tinKeyPressed

    private void nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyReleased
       int p=nom.getCaretPosition();
       nom.setText(nom.getText().toUpperCase());
       nom.setCaretPosition(p);
    }//GEN-LAST:event_nomKeyReleased

    private void adrasseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adrasseKeyReleased
     int p=adrasse.getCaretPosition();
       adrasse.setText(adrasse.getText().toUpperCase());
       adrasse.setCaretPosition(p);
    }//GEN-LAST:event_adrasseKeyReleased

    private void nrcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrcKeyReleased
       int p=nrc.getCaretPosition();
       nrc.setText(nrc.getText().toUpperCase());
       nrc.setCaretPosition(p);
    }//GEN-LAST:event_nrcKeyReleased

    private void aiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aiKeyReleased
   int p=ai.getCaretPosition();
       ai.setText(ai.getText().toUpperCase());
       ai.setCaretPosition(p);        // TODO add your handling code here:
    }//GEN-LAST:event_aiKeyReleased

    private void aifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aifKeyReleased
       int p=aif.getCaretPosition();
       aif.setText(aif.getText().toUpperCase());
       aif.setCaretPosition(p);
    }//GEN-LAST:event_aifKeyReleased

    private void nisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nisKeyReleased
   int p=nis.getCaretPosition();
       nis.setText(nis.getText().toUpperCase());
       nis.setCaretPosition(p);        // TODO add your handling code here:
    }//GEN-LAST:event_nisKeyReleased

    private void tinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tinKeyReleased
   int p=tin.getCaretPosition();
       tin.setText(tin.getText().toUpperCase());
       tin.setCaretPosition(p);        // TODO add your handling code here:
    }//GEN-LAST:event_tinKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
  Home c=new Home();
        c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\bay.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(1800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMiActionPerformed
try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\quitte fournisseur.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
        this.setState(JFrame.ICONIFIED);    
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdMiActionPerformed

    private void srchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srchKeyReleased
 int p=srch.getCaretPosition();
       srch.setText(srch.getText().toUpperCase());
       srch.setCaretPosition(p);        // TODO add your handling code here:
    }//GEN-LAST:event_srchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fournniseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fournniseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fournniseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fournniseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fournniseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tabledark.TableDark TBF;
    private textfield.TextField adrasse;
    private textfield.TextField ai;
    private textfield.TextField aif;
    private com.raven.swing.win_button.Button cmdClose;
    private com.raven.swing.win_button.Button cmdMi;
    private textfield.TextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private textfield.TextField mobile;
    private button.Button nf;
    private textfield.TextField nis;
    private textfield.TextField nom;
    private textfield.TextField nrc;
    private textfield.TextField srch;
    private textfield.TextField tin;
    // End of variables declaration//GEN-END:variables
}
