
package IHM;

import ConnectionDB.ConnectDB;
import com.raven.chart.ModelChart;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;








public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        icon();
      getContentPane().setBackground(new Color(250, 250, 250));
        chart.addLegend("BENEFICE", new Color(245, 189, 135));
        chart.addLegend("ACHAT", new Color(135, 189, 245));
        chart.addLegend("VENT", new Color(139, 229, 222));
        chart.addData(new ModelChart("Janvier", new double[]{89, 200, 500}));
        chart.addData(new ModelChart("Février", new double[]{150, 250,  600}));
        chart.addData(new ModelChart("Mars", new double[]{200, 350,  900}));
        chart.addData(new ModelChart("Avril", new double[]{180, 450,  700}));
        chart.addData(new ModelChart("May", new double[]{350, 240,  540}));
        chart.addData(new ModelChart("Jeanne", new double[]{190, 280,  400}));
      
        showDate();
       showTime();
       setExtendedState(JFrame.MAXIMIZED_HORIZ);
    }ConnectDB db;
      void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().
                getResource("iconapp.png")));
    }
void showDate(){
    Date d=new Date();
    SimpleDateFormat sdf=new SimpleDateFormat("E dd-MM-YYYY");
    jLabel2.setText(sdf.format(d));
            
}
void showTime(){
    new Timer(0,new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date d=new Date();
             SimpleDateFormat sdf=new SimpleDateFormat("hh:mm:ss a");
    jLabel3.setText(sdf.format(d));
        }
    }).start();
}
public static double calculerPourcentage(double valeur) {
    double pourcentage = (valeur / 5000) * 100;
    return pourcentage;
}
public static double calculerPourcentagev(double valeur) {
    double pourcentage = (valeur / 50000) * 100;
    return pourcentage;
}
public static double calculerPourcentageb(double valeur) {
//    double pourcentage = (valeur / 50000) * 100;
    double pourc = (calculerPourcentage(valeur) * 5000 + calculerPourcentagev(valeur) * 50000) / 55000 ;
    double pourcentage = (pourc / 500) * 100;
    return pourcentage;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cmdClose = new com.raven.swing.win_button.Button();
        cmdMi = new com.raven.swing.win_button.Button();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javaswingdev.uwp.UWPButton();
        uWPButton2 = new javaswingdev.uwp.UWPButton();
        uWPButton3 = new javaswingdev.uwp.UWPButton();
        uWPButton4 = new javaswingdev.uwp.UWPButton();
        uWPButton5 = new javaswingdev.uwp.UWPButton();
        uWPButton7 = new javaswingdev.uwp.UWPButton();
        jButton1 = new javax.swing.JButton();
        uWPButton1 = new javaswingdev.uwp.UWPButton();
        liquidProgress1 = new swing.LiquidProgress();
        liquidProgress2 = new swing.LiquidProgress();
        liquidProgress3 = new swing.LiquidProgress();
        chart = new com.raven.chart.Chart();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(17, 114, 169));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Downloads\\home.png")); // NOI18N
        jLabel1.setText("Accueil");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clock (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("time");
        jLabel3.setPreferredSize(new java.awt.Dimension(59, 24));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/date.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("date");

        jPanel7.setBackground(new java.awt.Color(17, 114, 169));

        cmdClose.setBackground(new java.awt.Color(240, 61, 61));
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });

        cmdMi.setBackground(new java.awt.Color(227, 226, 68));
        cmdMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 60));

        jPanel3.setBackground(new java.awt.Color(17, 114, 169));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\meilleur-homme.png")); // NOI18N
        jButton2.setText("Client");
        jButton2.setAutoscrolls(true);
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        uWPButton2.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\livreur.png")); // NOI18N
        uWPButton2.setText("FOURNISSEUR");
        uWPButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton2ActionPerformed(evt);
            }
        });

        uWPButton3.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\marche (1).png")); // NOI18N
        uWPButton3.setText("ACHAT");
        uWPButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton3ActionPerformed(evt);
            }
        });

        uWPButton4.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\carte-de-credit (1).png")); // NOI18N
        uWPButton4.setText("VENTE");
        uWPButton4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton4ActionPerformed(evt);
            }
        });

        uWPButton5.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\retour-dinformation.png")); // NOI18N
        uWPButton5.setText("PRODUIT");
        uWPButton5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton5ActionPerformed(evt);
            }
        });

        uWPButton7.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Downloads\\2720641 (2).png")); // NOI18N
        uWPButton7.setText("SERVICE");
        uWPButton7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton7ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Desktop\\icon\\utilisateurs.png")); // NOI18N
        jButton1.setText("utilisateur");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        uWPButton1.setForeground(new java.awt.Color(0, 0, 0));
        uWPButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\soulaimane\\Downloads\\coding.png")); // NOI18N
        uWPButton1.setText("developeur");
        uWPButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 20)); // NOI18N
        uWPButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uWPButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        uWPButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uWPButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(uWPButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uWPButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uWPButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uWPButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(uWPButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(uWPButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(uWPButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uWPButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(uWPButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(uWPButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uWPButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uWPButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, 900));

        liquidProgress1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                liquidProgress1PropertyChange(evt);
            }
        });
        jPanel1.add(liquidProgress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 210, 140));

        liquidProgress2.setAnimateColor(new java.awt.Color(245, 189, 135));
        liquidProgress2.setBorderColor(new java.awt.Color(245, 189, 135));
        jPanel1.add(liquidProgress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, 220, 140));

        liquidProgress3.setForeground(new java.awt.Color(0, 204, 204));
        liquidProgress3.setAnimateColor(new java.awt.Color(9, 251, 178));
        liquidProgress3.setBorderColor(new java.awt.Color(0, 255, 156));
        jPanel1.add(liquidProgress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 130, 230, 140));

        chart.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        chart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                chartPropertyChange(evt);
            }
        });
        jPanel1.add(chart, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 930, 560));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 178, 255));
        jLabel6.setText("ACHAT AUJOURD'HUI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 189, 135));
        jLabel7.setText("BENEFICE AUJOURD'HUI");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 190, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 204));
        jLabel8.setText("VENTE AUJOURD'HUI");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      db =new ConnectDB();
       db.ConnexionIntoDataBase();
       double vl = 0;
       double v2 = 0;
       double v3 =0;
        try {
            vl = db.RMDAJ();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        double valeur =vl;     
double resultat = calculerPourcentage(valeur);
        liquidProgress1.setValue((int) resultat);
        
        
         try {
            v2 = db.RMDVJ();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
          double val = v2;
          double resultat1 = calculerPourcentagev(val);
          liquidProgress3.setValue((int) resultat1);
          
         try {
            v3 = db.RMDVJ();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } 
          double val1 = v3;
          double resultat2 = resultat1-resultat;
          liquidProgress2.setValue((int) resultat2);
          try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\bienvenue.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(1500);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void chartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_chartPropertyChange
chart.start();        // TODO add your handling code here:
    }//GEN-LAST:event_chartPropertyChange

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
        try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\bay.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void cmdMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMiActionPerformed
        this.setState(JFrame.ICONIFIED);    
        this.setVisible(false);
    try {
            File songFile = new File("C:\\Users\\soulaimane\\Desktop\\DispalyBAhai\\JavaApplication2\\src\\son\\bay.wav"); // Replace with the actual path to your song file

            Clip clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(songFile));
            clip.start();
             Thread.sleep(800);
//            JOptionPane.showMessageDialog(this, "Song is playing. Click OK to stop.");
            clip.stop();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error playing song: " + e.getMessage());
        } 
    LOGIN f=new LOGIN();
f.setVisible(true); 
    }//GEN-LAST:event_cmdMiActionPerformed

    private void uWPButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton1ActionPerformed
     developpeurr v=new developpeurr();
        v.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 Client c=new Client();
 
        c.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void uWPButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton2ActionPerformed
Fournniseur f=new Fournniseur();
f.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton2ActionPerformed

    private void uWPButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton3ActionPerformed
Achat a=new Achat();
a.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton3ActionPerformed

    private void uWPButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton4ActionPerformed
   Vent v=new Vent();
        v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton4ActionPerformed

    private void uWPButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton5ActionPerformed
Produit p = new Produit();
p.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton5ActionPerformed

    private void uWPButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uWPButton7ActionPerformed
Service v=new Service();
        v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_uWPButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
GestionUtilisateur v=new GestionUtilisateur();
        v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void liquidProgress1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_liquidProgress1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_liquidProgress1PropertyChange

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    private com.raven.swing.win_button.Button cmdClose;
    private com.raven.swing.win_button.Button cmdMi;
    public javax.swing.JButton jButton1;
    private javaswingdev.uwp.UWPButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private swing.LiquidProgress liquidProgress1;
    private swing.LiquidProgress liquidProgress2;
    private swing.LiquidProgress liquidProgress3;
    private javaswingdev.uwp.UWPButton uWPButton1;
    private javaswingdev.uwp.UWPButton uWPButton2;
    private javaswingdev.uwp.UWPButton uWPButton3;
    private javaswingdev.uwp.UWPButton uWPButton4;
    private javaswingdev.uwp.UWPButton uWPButton5;
    private javaswingdev.uwp.UWPButton uWPButton7;
    // End of variables declaration//GEN-END:variables

    Object getuWPButton6() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
